name: panda_helper
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.13
    - beautifulsoup4=4.12.3
    - black=24.8.0
    - codespell
    - coverage=7.6.9
    - jupyter=1.1.1
    - lxml=5.3.0
    - mkdocs=1.6.1
    - notebook=7.3.2
    - numpy=2.2.2
    - pandas=2.2.3
    - pip=24.2
    - pre-commit=4.1.0
    - pylint=3.3.4
    - pytest=7.4.4
    - python-build=1.2.2.post1
    - ruff=0.3.5
    - scipy=1.15.1
    - twine=5.1.1
    - pip:
        - mkdocs-material==9.6.2
        - mkdocstrings==0.28.0
        - mkdocstrings-python==1.14.5
        - tabulate==0.9.0
